[project]
name = 'Blockchain-Based-Specialized-Gemstone-Certification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.laboratory-verification]
path = 'contracts/laboratory-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.stone-registration]
path = 'contracts/stone-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.treatment-disclosure]
path = 'contracts/treatment-disclosure.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
